### ISSUE TITLE
RedisGraph 2.0

### ISSUE THREAD

**Issue by gkorland** [xyxel/RedisGraph.jl#2]
Hi @xyxel
Thanks for the work on this project!
We are about to release 2.0 officially, so I just wanted to give heads up. We changed our resultset structure significantly from 1.x, so the old protocol is not supported anymore.
In case you have any questions, you can reach me at our repo issues page or directly by mail.
Cheers!

**Comment by xyxel** [comment]
Hi @gkorland,
Thank you for your notice and sorry for the late response!
I've updated the package according to new protocol. Map and point support is coming soon.

**Comment by ShalokShalom** [comment]
Hi 👍🏻 

Is map and point implemented by now?

**Comment by xyxel** [comment]
Hi,

Yes, map and point are implemented. But pay attention, the last redisgraph version, that I used, was 2.4
Thank you.

**Comment by ShalokShalom** [comment]
So we may close this, and maybe also launch a new release? 😃

**Comment by xyxel** [comment]
Hi,

Do you mean just to launch a release or do you want to support of new features of redisgraph?

**Comment by ShalokShalom** [comment]
A new release. 👍🏻 

RedisGraph is in maintenance mode, so it does not come up with new features. 
It is succeeded at https://github.com/FalkorDB/FalkorDB/ if anyone is interested. 

Would be just nice, to have an option for the upcoming time till the EOL. 
As its relatively simply, to release the current state of the repo. :)

**Comment by xyxel** [comment]
I've released the current state. I will look at new features of RedisGraph and FalkorDB and update the client.
Thank you.
