### ISSUE TITLE
Being nice with Julia's newcommers

### ISSUE THREAD

**Issue by widged** [xyxel/RedisGraph.jl#4]
If you were keen to make it friendly to Julia newcommers, you could add the following in your readme. 

------------------------------------------

1/ redisgraph needs to be running

docker run -p 6379:6379 -it --rm redislabs/redisgraph

cf https://docs.redislabs.com/latest/modules/redisgraph/redisgraph-quickstart/

2/ add the Redis Package

julia> ]
pkg> add Redis

3/ add RedisGraph from the github repo

pkg> add https://github.com/xyxel/RedisGraph.jl

------------------------------------------

Thanks for making this available!
Marielle

**Comment by xyxel** [comment]
Hi Marielle,

Thank you for your comment! I've added section to Readme.md
By the way, in the Project.toml file there is Redis dependency, so the package should be downloaded automatically by Pkg.jl. Did you check setup without p.2 ("add the Redis Package") or something went wrong in your case?
Thank you!

**Comment by widged** [comment]
Hi,

I had followed a process of guessing. I checked on the Julia Box that I have on https://www.katacoda.com/widged/scenarios/julia-sandbox (guaranteed to have nothing pre-installed)

When I tried `pkg> add https://github.com/xyxel/RedisGraph.jl` and then your demo code, I got "ERROR: UndefVarError: Redis not defined". If I follow up with `pkg> add Redis`, all worked fine.

**Comment by xyxel** [comment]
Dear Marielle,

I've fixed this issue and updated Readme.md. So now you don't need to add Redis.jl explicitly.
Thank you for your feedback.

**Comment by ShalokShalom** [comment]
Can we close this, now?
